### ISSUE TITLE
Different HTTP response for each request

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/Stubmatic#10]
Currently, a user can create the mapping to serve the response from random files or in a round-robin fashion. ([wiki](https://github.com/NaturalIntelligence/Stubmatic/wiki/04.0-Response-Resolution-Strategy))
```yaml
-  request:
      url: /stubs/employee/([0-9]+)

   response:
      strategy: random
      files: ["<% url.1 %>.xml","file2.xml","file3.xml"]
```
Or
```yaml
-  request:
      url: /stubs/employee/([0-9]+)

   response:
      strategy: random
      files: ["<% url.1 %>.xml","file2.xml",{"name":"file3.xml","status":500}]
```
But what if a user wants the same behavior but without any response in the body? He can create an empty file and do a hack like this;

```yaml
-  request:
      url: /stubs/employee/([0-9]+)

   response:
      strategy: random
      files: [{"name":"empty","status":500}, {"name":"empty","status":503}]
```

We're looking for some meaningful mapping

```yaml
-  request:
      url: /stubs/employee/([0-9]+)

   response:
      strategy: random
      status: [ 500, 503 ]
```
