### ISSUE TITLE
direct debug HTTP roundtrip without any configuration or mocks

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/Stubmatic#6]
Currently stubmatic can be used to debug a HTTP request without setting up any workspace;

```bash
$ stubmatic -v --debug [-p XXXX]
```
It also supports [proxy](https://github.com/NaturalIntelligence/Stubmatic/blob/master/lib/server.js#L141) a request to other server.

```yaml
-  request:
      url: /someurl/.*

   response:
      proxy: http://google.com:8003
```

The combined feature can be used to debug HTTP response;

```bash
$ stubmatic -v --debug [-p XXXX] --to http://google.com
```

**Requirement** : When a user runs stubmatic with argument `to`, it should ignore any request response mapping. and should work as a proxy. if the `--debug` parameter is passed then it should log everything to the console or output stream.
